//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub public_key: String,
    #[sea_orm(unique)]
    pub private_key: String,
    pub password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mails::Entity")]
    Mails,
}

impl Related<super::mails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
